// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: TempSensor

#include "ui.h"
#include "ui_helpers.h"
#include "../../inc/queue.h"
#include "../../inc/sensors.h"
#include <stdio.h>
#include <zephyr/kernel.h>

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_Image1;
lv_obj_t * ui_LabelSensor;
lv_obj_t * ui_LabelTemp;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 32
    #error "LV_COLOR_DEPTH should be 32bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

/* Reference the semaphore declared in main.c */
extern struct k_sem ui_ready_sem;

/**
 * @brief Process all messages in temperature queue and update UI
 * 
 * This function retrieves all available messages from the temperature queue
 * and updates the corresponding UI elements.
 */
void process_queue(void)
{
    sensor_msg_t msg;
    char temp_str[32];
    char humidity_str[32];
    bool temp_updated = false;
    bool humidity_updated = false;
    struct k_msgq *temp_msgq = get_temp_msgq();
    
    if (temp_msgq == NULL) {
        return;
    }
    
    /* Process all messages in the queue */
    while (k_msgq_get(temp_msgq, &msg, K_NO_WAIT) == 0) {
        switch(msg.type) {
        case MSG_TYPE_TEMPERATURE:
            /* Update temperature string */
            snprintf(temp_str, sizeof(temp_str), "Temperature: %.1f °C", msg.value);
            temp_updated = true;
            break;
            
        case MSG_TYPE_HUMIDITY:
            /* Update humidity string */
            snprintf(humidity_str, sizeof(humidity_str), "Humidity: %.1f%%", msg.value);
            humidity_updated = true;
            break;
            
        default:
            /* Unknown message type */
            break;
        }
    }
    
    /* Update the temperature label if new data is available */
    if (temp_updated && ui_LabelTemp != NULL) {
        lv_label_set_text(ui_LabelTemp, temp_str);
    }
    
    /* Update the humidity label if new data is available */
    if (humidity_updated && ui_LabelSensor != NULL) {
        lv_label_set_text(ui_LabelSensor, humidity_str);
    }
    
    /* Alternative approach: directly access the sensor values */
    double temperature, humidity;
    
    /* Get latest temperature and update UI if available */
    if (!temp_updated && get_latest_temperature(&temperature) && ui_LabelTemp != NULL) {
        snprintf(temp_str, sizeof(temp_str), "Temperature: %.1f °C", temperature);
        lv_label_set_text(ui_LabelTemp, temp_str);
    }
    
    /* Get latest humidity and update UI if available */
    if (!humidity_updated && get_latest_humidity(&humidity) && ui_LabelSensor != NULL) {
        snprintf(humidity_str, sizeof(humidity_str), "Humidity: %.1f%%", humidity);
        lv_label_set_text(ui_LabelSensor, humidity_str);
    }
}

void ui_init(void)
{
    printk("UI initialization started\n");

    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
    
    printk("UI initialization completed\n");
}

void ui_thread_entry(void *p1, void *p2, void *p3)
{
    printk("UI thread started\n");
    
    /* Initialize default labels if necessary */
    if (ui_LabelTemp != NULL) {
        lv_label_set_text(ui_LabelTemp, "Temperature: --.- °C");
    }
    
    if (ui_LabelSensor != NULL) {
        lv_label_set_text(ui_LabelSensor, "Humidity: --.-%");
    }
    
    while (1) {
        /* Process sensor data from queue */
        process_queue();
        
        /* Sleep for a short time */
        k_sleep(K_MSEC(100));
    }
}