// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: TempSensor

#ifndef _TEMPSENSOR_UI_H
#define _TEMPSENSOR_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_LabelSensor;
extern lv_obj_t * ui_LabelTemp;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_1780325426);    // assets/Capture d'écran 2025-03-21 113557.png

// UI INIT
void ui_init(void);

/**
 * @brief Entry function for the UI thread
 */
void ui_thread_entry(void *p1, void *p2, void *p3);

/**
 * @brief Process and display temperature from the message queue
 */
void process_queue(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
