// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Proj_test

#include "../ui.h"

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Clock_Group1 = lv_obj_create(ui_Screen4);
    lv_obj_set_width(ui_Clock_Group1, 244);
    lv_obj_set_height(ui_Clock_Group1, 244);
    lv_obj_set_align(ui_Clock_Group1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Clock_Group1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Clock_Group1, 10000, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Clock_Group1, lv_color_hex(0x262F29), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Clock_Group1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Accelerometre = lv_label_create(ui_Clock_Group1);
    lv_obj_set_width(ui_Accelerometre, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Accelerometre, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Accelerometre, 0);
    lv_obj_set_y(ui_Accelerometre, -60);
    lv_obj_set_align(ui_Accelerometre, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Accelerometre, "Accelerometre :");
    lv_obj_set_style_text_color(ui_Accelerometre, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Accelerometre, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_accel_x = lv_label_create(ui_Clock_Group1);
    lv_obj_set_width(ui_accel_x, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_accel_x, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_accel_x, -70);
    lv_obj_set_y(ui_accel_x, -20);
    lv_obj_set_align(ui_accel_x, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_accel_x, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_accel_x, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_accel_y = lv_label_create(ui_Clock_Group1);
    lv_obj_set_width(ui_accel_y, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_accel_y, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_accel_y, 0);
    lv_obj_set_y(ui_accel_y, -20);
    lv_obj_set_align(ui_accel_y, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_accel_y, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_accel_y, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_accel_z = lv_label_create(ui_Clock_Group1);
    lv_obj_set_width(ui_accel_z, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_accel_z, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_accel_z, 70);
    lv_obj_set_y(ui_accel_z, -20);
    lv_obj_set_align(ui_accel_z, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_accel_z, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_accel_z, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Gyroscope = lv_label_create(ui_Clock_Group1);
    lv_obj_set_width(ui_Gyroscope, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Gyroscope, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Gyroscope, 1);
    lv_obj_set_y(ui_Gyroscope, 20);
    lv_obj_set_align(ui_Gyroscope, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Gyroscope, "Gyroscope :");
    lv_obj_set_style_text_color(ui_Gyroscope, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Gyroscope, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gyro_x = lv_label_create(ui_Clock_Group1);
    lv_obj_set_width(ui_gyro_x, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gyro_x, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gyro_x, -70);
    lv_obj_set_y(ui_gyro_x, 60);
    lv_obj_set_align(ui_gyro_x, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_gyro_x, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gyro_x, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gyro_y = lv_label_create(ui_Clock_Group1);
    lv_obj_set_width(ui_gyro_y, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gyro_y, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gyro_y, 0);
    lv_obj_set_y(ui_gyro_y, 60);
    lv_obj_set_align(ui_gyro_y, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_gyro_y, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gyro_y, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gyro_z = lv_label_create(ui_Clock_Group1);
    lv_obj_set_width(ui_gyro_z, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gyro_z, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gyro_z, 70);
    lv_obj_set_y(ui_gyro_z, 60);
    lv_obj_set_align(ui_gyro_z, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_gyro_z, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gyro_z, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
}
