// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Proj_test

#include "../ui.h"

void ui_Screen7_screen_init(void)
{
    ui_Screen7 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Clock_Group5 = lv_obj_create(ui_Screen7);
    lv_obj_set_width(ui_Clock_Group5, 244);
    lv_obj_set_height(ui_Clock_Group5, 244);
    lv_obj_set_align(ui_Clock_Group5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Clock_Group5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Clock_Group5, 10000, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Clock_Group5, lv_color_hex(0x262F29), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Clock_Group5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_month = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_month, LV_SIZE_CONTENT);   /// 5
    lv_obj_set_height(ui_month, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_month, 49);
    lv_obj_set_y(ui_month, -74);
    lv_obj_set_align(ui_month, LV_ALIGN_CENTER);
    lv_label_set_text(ui_month, "Janvier");
    lv_obj_set_style_text_color(ui_month, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_month, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lundi = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_lundi, LV_SIZE_CONTENT);   /// 5
    lv_obj_set_height(ui_lundi, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_lundi, -95);
    lv_obj_set_y(ui_lundi, -50);
    lv_obj_set_align(ui_lundi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lundi, "L");
    lv_obj_set_style_text_color(ui_lundi, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lundi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mardi = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_mardi, LV_SIZE_CONTENT);   /// 5
    lv_obj_set_height(ui_mardi, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_mardi, -64);
    lv_obj_set_y(ui_mardi, -50);
    lv_obj_set_align(ui_mardi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_mardi, "M");
    lv_obj_set_style_text_color(ui_mardi, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_mardi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mercredi = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_mercredi, LV_SIZE_CONTENT);   /// 5
    lv_obj_set_height(ui_mercredi, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_mercredi, -32);
    lv_obj_set_y(ui_mercredi, -50);
    lv_obj_set_align(ui_mercredi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_mercredi, "M");
    lv_obj_set_style_text_color(ui_mercredi, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_mercredi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_jeudi = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_jeudi, LV_SIZE_CONTENT);   /// 5
    lv_obj_set_height(ui_jeudi, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_jeudi, 0);
    lv_obj_set_y(ui_jeudi, -50);
    lv_obj_set_align(ui_jeudi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_jeudi, "J");
    lv_obj_set_style_text_color(ui_jeudi, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_jeudi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_vendredi = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_vendredi, LV_SIZE_CONTENT);   /// 5
    lv_obj_set_height(ui_vendredi, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_vendredi, 31);
    lv_obj_set_y(ui_vendredi, -50);
    lv_obj_set_align(ui_vendredi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_vendredi, "V");
    lv_obj_set_style_text_color(ui_vendredi, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_vendredi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_samedi = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_samedi, LV_SIZE_CONTENT);   /// 5
    lv_obj_set_height(ui_samedi, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_samedi, 63);
    lv_obj_set_y(ui_samedi, -50);
    lv_obj_set_align(ui_samedi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_samedi, "S");
    lv_obj_set_style_text_color(ui_samedi, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_samedi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dimanche = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_dimanche, LV_SIZE_CONTENT);   /// 5
    lv_obj_set_height(ui_dimanche, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_dimanche, 94);
    lv_obj_set_y(ui_dimanche, -50);
    lv_obj_set_align(ui_dimanche, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dimanche, "D");
    lv_obj_set_style_text_color(ui_dimanche, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dimanche, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}
