// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Proj_test

#include "../ui.h"

void ui_Screen6_screen_init(void)
{
    ui_Screen6 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Clock_Group4 = lv_obj_create(ui_Screen6);
    lv_obj_set_width(ui_Clock_Group4, 244);
    lv_obj_set_height(ui_Clock_Group4, 244);
    lv_obj_set_align(ui_Clock_Group4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Clock_Group4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Clock_Group4, 10000, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Clock_Group4, lv_color_hex(0x262F29), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Clock_Group4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chronometre = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_Chronometre, LV_SIZE_CONTENT);   /// 5
    lv_obj_set_height(ui_Chronometre, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_Chronometre, 0);
    lv_obj_set_y(ui_Chronometre, -50);
    lv_obj_set_align(ui_Chronometre, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_Chronometre, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Chronometre, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Chronometre, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_chronometreActi = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_chronometreActi, LV_SIZE_CONTENT);   /// 5
    lv_obj_set_height(ui_chronometreActi, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_chronometreActi, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_chronometreActi, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_chronometreActi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_chronometreActi, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_distance = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_distance, LV_SIZE_CONTENT);   /// 5
    lv_obj_set_height(ui_distance, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_distance, 0);
    lv_obj_set_y(ui_distance, 50);
    lv_obj_set_align(ui_distance, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_distance, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_distance, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_test = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_test, LV_SIZE_CONTENT);   /// 5
    lv_obj_set_height(ui_test, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_test, -90);
    lv_obj_set_y(ui_test, 0);
    lv_obj_set_align(ui_test, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_test, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_test, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}
