// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Proj_test

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HourLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_HourLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HourLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HourLabel, -2);
    lv_obj_set_y(ui_HourLabel, -97);
    lv_obj_set_align(ui_HourLabel, LV_ALIGN_CENTER);

    ui_LabelSensor = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelSensor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSensor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSensor, -82);
    lv_obj_set_y(ui_LabelSensor, -58);
    lv_obj_set_align(ui_LabelSensor, LV_ALIGN_CENTER);

    ui_LabelTemp = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTemp, 74);
    lv_obj_set_y(ui_LabelTemp, -56);
    lv_obj_set_align(ui_LabelTemp, LV_ALIGN_CENTER);

    ui_Label4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -110);
    lv_obj_set_y(ui_Label4, -8);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);

    ui_Label5 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 0);
    lv_obj_set_y(ui_Label5, -10);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);

    ui_Label6 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 98);
    lv_obj_set_y(ui_Label6, -7);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);

    ui_Label7 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -109);
    lv_obj_set_y(ui_Label7, 44);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);

    ui_Label8 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 0);
    lv_obj_set_y(ui_Label8, 42);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);

    ui_Label9 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 101);
    lv_obj_set_y(ui_Label9, 41);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);

    ui_Label10 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -73);
    lv_obj_set_y(ui_Label10, 88);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);

    ui_Label11 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 83);
    lv_obj_set_y(ui_Label11, 92);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);

}
