// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Proj_test

#include "../ui.h"

void ui_Screen5_screen_init(void)
{
    ui_Screen5 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Clock_Group3 = lv_obj_create(ui_Screen5);
    lv_obj_set_width(ui_Clock_Group3, 244);
    lv_obj_set_height(ui_Clock_Group3, 244);
    lv_obj_set_align(ui_Clock_Group3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Clock_Group3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Clock_Group3, 10000, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Clock_Group3, lv_color_hex(0x262F29), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Clock_Group3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Magnetisme = lv_label_create(ui_Clock_Group3);
    lv_obj_set_width(ui_Magnetisme, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Magnetisme, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Magnetisme, 0);
    lv_obj_set_y(ui_Magnetisme, -80);
    lv_obj_set_align(ui_Magnetisme, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Magnetisme, "Magnetisme :");
    lv_obj_set_style_text_color(ui_Magnetisme, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Magnetisme, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mag_x = lv_label_create(ui_Clock_Group3);
    lv_obj_set_width(ui_mag_x, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mag_x, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_mag_x, -70);
    lv_obj_set_y(ui_mag_x, -50);
    lv_obj_set_align(ui_mag_x, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_mag_x, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_mag_x, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mag_y = lv_label_create(ui_Clock_Group3);
    lv_obj_set_width(ui_mag_y, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mag_y, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_mag_y, 0);
    lv_obj_set_y(ui_mag_y, -50);
    lv_obj_set_align(ui_mag_y, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_mag_y, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_mag_y, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mag_z = lv_label_create(ui_Clock_Group3);
    lv_obj_set_width(ui_mag_z, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mag_z, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_mag_z, 70);
    lv_obj_set_y(ui_mag_z, -50);
    lv_obj_set_align(ui_mag_z, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_mag_z, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_mag_z, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}
