// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: TempSensor

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image1, &ui_img_1780325426);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 128
    lv_obj_set_x(ui_Image1, 3);
    lv_obj_set_y(ui_Image1, -11);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image1, 128);

    ui_LabelSensor = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelSensor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSensor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSensor, 4);
    lv_obj_set_y(ui_LabelSensor, -97);
    lv_obj_set_align(ui_LabelSensor, LV_ALIGN_CENTER);

    ui_LabelTemp = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTemp, 5);
    lv_obj_set_y(ui_LabelTemp, 75);
    lv_obj_set_align(ui_LabelTemp, LV_ALIGN_CENTER);

}
