// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Proj_test

#include "../ui.h"

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Clock_Group2 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_Clock_Group2, 244);
    lv_obj_set_height(ui_Clock_Group2, 244);
    lv_obj_set_align(ui_Clock_Group2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Clock_Group2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Clock_Group2, 10000, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Clock_Group2, lv_color_hex(0x262F29), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Clock_Group2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HourLabel = lv_label_create(ui_Clock_Group2);
    lv_obj_set_width(ui_HourLabel, LV_SIZE_CONTENT);   /// 5
    lv_obj_set_height(ui_HourLabel, LV_SIZE_CONTENT);    /// 5
    lv_obj_set_x(ui_HourLabel, 0);
    lv_obj_set_y(ui_HourLabel, 0);
    lv_obj_set_align(ui_HourLabel, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_HourLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HourLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HourLabel, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTemp = lv_label_create(ui_Clock_Group2);
    lv_obj_set_width(ui_LabelTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTemp, 70);
    lv_obj_set_y(ui_LabelTemp, -50);
    lv_obj_set_align(ui_LabelTemp, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_LabelTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelHumi = lv_label_create(ui_Clock_Group2);
    lv_obj_set_width(ui_LabelHumi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHumi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHumi, -70);
    lv_obj_set_y(ui_LabelHumi, -50);
    lv_obj_set_align(ui_LabelHumi, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_LabelHumi, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHumi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}
